title: LSTM Stock Price Predictor
emoji: 📈
colorFrom: blue
colorTo: green
sdk: gradio
sdk_version: 4.0.0
app_file: app.py
pinned: false
license: mit
short_description: AI-powered stock price prediction using LSTM neural networks